### ISSUE TITLE
 consul no route to host

### ISSUE THREAD

**Issue by alxlv** [hypriot/rpi-registrator#2]
Hi guys,

I'm trying to run registrator container on rpi2 but get the following message:
# sudo docker run -i -v /var/run/docker.sock:/var/run/docker.sock hypriot/rpi-registrator -internal consul://192.168.2.1:8500

2016/03/06 21:02:05 Starting registrator v6 ...
2016/03/06 21:02:08 consul: Get http://192.168.2.1:8500/v1/status/leader: dial tcp 192.168.2.1:8500: no route to host

The curl shows me the response:
# curl http://192.168.2.1:8500/v1/status/leader

"192.168.2.1:8300"

Any ideas? Thx.

**Comment by firecyberice** [comment]
How is your network setup?
Is this 192.168.2.1 IP one of your LAN at home?

Which IP addresses and routes are available in a registrator container?
`docker run -it --name registrator -v /var/run/docker.sock:/var/run/docker.sock hypriot/rpi-registrator -internal consul://192.168.2.1:8500`
`docker exec -it registrator bash`
And then in this container you can check the routes and ip addresses via `ip route`and `ip address show`.

**Comment by alxlv** [comment]
Here is the output for cmd:
#sudo docker run -it --name registrator -v /var/run/docker.sock:/var/run/docker.sock hypriot/rpi-registrator -internal consul://192.168.2.1:8500
2016/03/09 16:50:22 Starting registrator v6 ...
2016/03/09 16:50:25 consul: Get http://192.168.2.1:8500/v1/status/leader: dial tcp 192.168.2.1:8500: no route to host

But if I enter cmd it returns the string:
#curl http://192.168.2.1:8500/v1/status/leader
"192.168.2.1:8300"

Yep, that's my gateway (192.168.2.1). I have two interfaces on this machine:
- wifi 172.x.x.1
- eth0 192.168.2.1

The consul is running on eth0 and works fine. The rpi2 device is in my 192.168.2.0/24 subnet and has IP address 192.168.2.10. I'm able to ping 192.168.2.1 machine and connect through ssh, the firewall is not enabled on gateway machine also.

**Comment by alxlv** [comment]
I was able to fix issue with network by passing --net parameter:
#sudo docker run -it --net=host --name registrator -v /var/run/docker.sock:/var/run/docker.sock hypriot/rpi-registrator -internal consul://192.168.2.1:8500
2016/03/09 20:08:03 Starting registrator v6 ...
2016/03/09 20:08:03 consul: current leader  192.168.2.1:8300
2016/03/09 20:08:03 Using consul adapter: consul://192.168.2.1:8500
2016/03/09 20:08:03 Listening for Docker events ...
2016/03/09 20:08:03 Get http://unix.sock/containers/json: dial unix /tmp/docker.sock: no such file or directory

By get the error - Get http://unix.sock/containers/json: dial unix /tmp/docker.sock: no such file or directory. Why does it try to connect using /tmp/docker.sock if I set /var/run/docker.sock value?

**Comment by alxlv** [comment]
At least I fixed it by following command (run as daemon):

#sudo docker run -d --net=host -v /tmp/docker.sock:/tmp/docker.sock hypriot/rpi-registrator -internal consul://192.168.2.1:8500
